https://zhuanlan.zhihu.com/p/36303821?utm_medium=social&utm_member=M2FkN2E3NWUwMzVmOGIwMTJhNDgzNTU0ZDJiYzIyNjc%3D&utm_source=wechat_session&from=message&isappinstalled=0

挑战 1：引入 numpy 并查看 numpy 的版本。  

要求：这是第一步，以后我们使用 numpy 时都将用别名 np。

In [1]:
import numpy as np 

In [2]:
np.__version__

'1.11.3'

In [3]:
np.version.version

'1.11.3'

挑战 2：创建数组
要求：创建一维数组，内容为从 0 到 9。

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

挑战 3：创建布尔数组
要求：数组大小为 3*3，全部为 True。

In [5]:
np.ones([3,3],dtype = np.bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)


挑战 4：按要求抽取数组中的元素  
要求：原数组为一维数组，内容为从 0 到 9，抽取出所有奇数。

方法1：

In [6]:
%timeit 5000000000000
np.arange(10)[1::2]

100000000 loops, best of 3: 18.5 ns per loop


array([1, 3, 5, 7, 9])

方法2:

In [7]:
%timeit 5000000000000
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
arr[arr%2 ==1]

10000000 loops, best of 3: 18.4 ns per loop


array([1, 3, 5, 7, 9])

以上效率基本还是一致的

In [8]:
挑战 5：按要求修改数组中的元素（原地修改）  
要求：原数组为一维数组，内容为从 0 到 9，将所有奇数原地修改为 -1。

SyntaxError: invalid syntax (<ipython-input-8-1ba393cb74c3>, line 1)

方法1：

In [ ]:
arr1 = np.arange(10)
arr1[1::2]= -1
arr1

方法2:

In [ ]:
arr2 = np.arange(10)
arr2[arr2%2 ==1] =-1
arr2

挑战 6：按要求修改数组中的元素（返回新数组）  
要求：原数组为一维数组，内容为从 0 到 9，返回一个该数组的拷贝，其中奇数修改为 -1。

In [ ]:
arr3 = np.arange(10)
arr4 = np.where(arr3%2==1 ,-1 ,arr3)
arr4

挑战 7：修改数组的形状  
要求：将给定的一维数组 reshape 为二维数组，其中新数组的行数为2。

In [ ]:
arr5 = np.arange(40).reshape(2,-1)
arr5

挑战 8：合并数组（列方向）  
要求：将给定数组在列方向上合并。

方法1：

In [ ]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
c = np.vstack([a,b])
c

方法2:

In [ ]:
c1 = np.concatenate([a, b], axis=0)
c1

挑战 9：合并数组（水平方向）
要求：将给定数组在水平方向上合并。

In [9]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)

In [10]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

方法1：

In [12]:
c1 = np.hstack([a,b])
c1

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

方法2:

In [13]:
c2 = np.concatenate([a,b],axis = 1)
c2

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

挑战 10：创建数组（进阶）

要求：不用硬编码，使用内置方法，从给定数组 a 生成数组 b。


In [14]:
# 输入数组
a = np.array([1,2,3])
b = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 答案
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

挑战 11：返回公共元素

要求：给定两个数组，要求返回这两个数组元素的交集。

In [15]:
# 输入数组
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 

In [17]:
#答案
c = np.intersect1d(a,b)
c

array([2, 4])

挑战 12：删除元素

要求：给定两个数组 a、b，从数组 a 中删除 b 中出现的元素。


In [18]:
# 输入数组
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 

In [20]:
c = np.setdiff1d(a,b)
c

array([1, 3, 5, 6])

挑战 13：找出相同元素

要求：给定两个数组 a、b，返回两数组中相同元素的下标。

In [22]:
# 输入数组
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 

In [23]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

挑战 14：按要求取出元素

要求：从数组中取出大于等于 5 且小于等于 10 的元素。

In [31]:
a = np.random.randint(-15,15,5)
a

array([  6,   4,   3, -10, -11])

In [35]:
# 答案 1: 
index = np.where((a >= 5) & (a <= 10)) 
a[index]  

# 答案 2: 
index = np.where(np.logical_and(a>=5, a<=10)) 
a[index] 

# 答案 3:
a[(a >= 5) & (a <= 10)]
#> (array([6, 9, 10]),)  

array([6])

挑战 15：实现 max 的 numpy 版

要求：给定长度相同的数组 a、b，返回一个新数组，数组上的每一个元素为 max(a_i, b_i)。

若 pair_max 为满足要求的函数，则对于 a 和 b，期望输出如下：



In [39]:
# 输入数组
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# 答案:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

挑战 16：交换二维数组的列

要求：交换数组的第一第二列。

In [54]:
arr = np.arange(9).reshape(3,3) 
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#这个方法比较蠢

a= arr[:,0].copy()
b= arr[:,1].copy()
a,b

arr[:,1] = a
arr[:,0] =b
arr

In [62]:
arr = np.arange(9).reshape(3,3) 
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

挑战 17：交换二维数组的行

要求：交换二维数组的第一第二行。

In [65]:
arr = np.arange(9).reshape(3,3)  
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

挑战 18：将一个数组按行反序

要求：数组 arr 为二维数组，将其行反序。

In [67]:
#输入数组
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

挑战 19：将一个数组按列反序

要求：数组 arr 为二维数组，将其列反序

In [74]:
# 输入数组
arr = np.arange(9).reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

挑战 20：创建随机数组

要求：创建一个 5*3 的数组，数组元素为 5 到 10 的随机浮点数。

In [82]:
# 答案 1: 
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3)) 
print(rand_arr)  


[[ 8.25757599  7.52459214  6.44564226]
 [ 7.51109338  5.66359111  5.99508472]
 [ 5.79606603  6.39378359  5.93929053]
 [ 9.74829623  8.03917397  8.0804582 ]
 [ 7.5006813   9.06356922  9.82372234]]


In [83]:
# 答案 2: 
rand_arr = np.random.uniform(5,10, size=(5,3)) 
print(rand_arr) 
#> [[ 8.50061025  9.10531502  6.85867783] 
#>  [ 9.76262069  9.87717411  7.13466701] 
#>  [ 7.48966403  8.33409158  6.16808631] 
#>  [ 7.75010551  9.94535696  5.27373226] 
#>  [ 8.0850361   5.56165518  7.31244004]]

[[ 8.79025651  7.85534488  9.51304781]
 [ 8.92024816  7.13708535  6.77399993]
 [ 5.70290837  5.62918482  5.87481908]
 [ 8.95014719  6.26365808  9.19839329]
 [ 5.38348726  8.48921874  9.1004861 ]]


挑战 21：按要求打印数组（一）

要求：数组元素输出时保留 3 位小数。

In [85]:
# 输入数组 
rand_arr = np.random.random([5,3]) 
rand_arr

array([[ 0.26861593,  0.9182402 ,  0.90720292],
       [ 0.80438972,  0.15390431,  0.35355657],
       [ 0.40690256,  0.11646059,  0.706493  ],
       [ 0.43501353,  0.02601024,  0.7658431 ],
       [ 0.10882497,  0.14993191,  0.08335108]])

In [86]:
# 答案：
# 设置保留 3 位小数 
np.set_printoptions(precision=3) 
rand_arr[:4] 

array([[ 0.269,  0.918,  0.907],
       [ 0.804,  0.154,  0.354],
       [ 0.407,  0.116,  0.706],
       [ 0.435,  0.026,  0.766]])

挑战 22：按要求打印数组（二）

要求：数组为小数，使用小数点的形式来打印，而不是科学记数法（如1e-4）。


In [87]:

# 输入数组
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[  5.434e-04,   2.784e-04,   4.245e-04],
       [  8.448e-04,   4.719e-06,   1.216e-04],
       [  6.707e-04,   8.259e-04,   1.367e-04]])

In [88]:
# 答案:
np.set_printoptions(suppress=True, precision=6)  # precision 是可选项
rand_arr
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

array([[ 0.000543,  0.000278,  0.000425],
       [ 0.000845,  0.000005,  0.000122],
       [ 0.000671,  0.000826,  0.000137]])

挑战 23：按要求打印数组（三）

要求：打印时省略中间元素，限制显示数组元素的个数为 6。



In [89]:

# 输入数组
a = np.arange(15)
#> 原输出 ：[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]
#> 目标输出：[ 0  1  2 ..., 12 13 14] array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
np.set_printoptions(threshold=6) 
a 

array([ 0,  1,  2, ..., 12, 13, 14])

挑战 24：加载特殊矩阵

要求：著名的 iris 数据集是包含兰花属性和种类的数据集，其中每行属性有数字和文字，用 numpy 来加载他们。

In [93]:
# 答案 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' 
iris = np.genfromtxt(url, delimiter=',', dtype='object') 
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')  
# 输出前三行 
iris[:3] 
iris
#> array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'], 
#>        [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'], 
#>        [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ..., 
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)