https://zhuanlan.zhihu.com/p/36303821?utm_medium=social&utm_member=M2FkN2E3NWUwMzVmOGIwMTJhNDgzNTU0ZDJiYzIyNjc%3D&utm_source=wechat_session&from=message&isappinstalled=0

挑战 1：引入 numpy 并查看 numpy 的版本。  

要求：这是第一步，以后我们使用 numpy 时都将用别名 np。

In [1]:
import numpy as np 

In [2]:
np.__version__

'1.11.3'

In [3]:
np.version.version

'1.11.3'

挑战 2：创建数组
要求：创建一维数组，内容为从 0 到 9。

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

挑战 3：创建布尔数组
要求：数组大小为 3*3，全部为 True。

In [5]:
np.ones([3,3],dtype = np.bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)


挑战 4：按要求抽取数组中的元素  
要求：原数组为一维数组，内容为从 0 到 9，抽取出所有奇数。

方法1：

In [6]:
%timeit 5000000000000
np.arange(10)[1::2]

100000000 loops, best of 3: 18.5 ns per loop


array([1, 3, 5, 7, 9])

方法2:

In [7]:
%timeit 5000000000000
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
arr[arr%2 ==1]

10000000 loops, best of 3: 18.4 ns per loop


array([1, 3, 5, 7, 9])

以上效率基本还是一致的

In [8]:
挑战 5：按要求修改数组中的元素（原地修改）  
要求：原数组为一维数组，内容为从 0 到 9，将所有奇数原地修改为 -1。

SyntaxError: invalid syntax (<ipython-input-8-1ba393cb74c3>, line 1)

方法1：

In [ ]:
arr1 = np.arange(10)
arr1[1::2]= -1
arr1

方法2:

In [ ]:
arr2 = np.arange(10)
arr2[arr2%2 ==1] =-1
arr2

挑战 6：按要求修改数组中的元素（返回新数组）  
要求：原数组为一维数组，内容为从 0 到 9，返回一个该数组的拷贝，其中奇数修改为 -1。

In [ ]:
arr3 = np.arange(10)
arr4 = np.where(arr3%2==1 ,-1 ,arr3)
arr4

挑战 7：修改数组的形状  
要求：将给定的一维数组 reshape 为二维数组，其中新数组的行数为2。

In [ ]:
arr5 = np.arange(40).reshape(2,-1)
arr5

挑战 8：合并数组（列方向）  
要求：将给定数组在列方向上合并。

方法1：

In [ ]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
c = np.vstack([a,b])
c

方法2:

In [ ]:
c1 = np.concatenate([a, b], axis=0)
c1

挑战 9：合并数组（水平方向）
要求：将给定数组在水平方向上合并。

In [9]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)

In [10]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

方法1：

In [12]:
c1 = np.hstack([a,b])
c1

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

方法2:

In [13]:
c2 = np.concatenate([a,b],axis = 1)
c2

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

挑战 10：创建数组（进阶）

要求：不用硬编码，使用内置方法，从给定数组 a 生成数组 b。


In [14]:
# 输入数组
a = np.array([1,2,3])
b = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 答案
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

挑战 11：返回公共元素

要求：给定两个数组，要求返回这两个数组元素的交集。

In [15]:
# 输入数组
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 

In [17]:
#答案
c = np.intersect1d(a,b)
c

array([2, 4])

挑战 12：删除元素

要求：给定两个数组 a、b，从数组 a 中删除 b 中出现的元素。
